# aks-deploys/podinfo/release.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: podinfo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: stefanprodan/podinfo:6.0.0
          ports:
            - containerPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: podinfo-app
spec:
  ports:
    - port: 80
      targetPort: 9898
  selector:
    app: podinfo
